#!/usr/bin/bash

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec startx
fi

export PERSO_BIN="$HOME/bin"
export PERSO_ENV="$HOME/.env/shell"

# env setup
HISTCONTROL=ignoreboth
HISTFILESIZE=-1
HISTSIZE=1000
shopt -s histappend

shopt -s checkwinsize # update `tput lines` & `tput cols` after each command
shopt -s globstar # wildcard behavior

tryload() {
    if [ -f "$1" ]; then
        . "$1"
        true
    else
        false
    fi
}
alias skip=true

if ! shopt -oq posix; then
    if tryload /usr/share/bash-completion/bash_completion; then
        skip
    elif tryload /etc/bash_completion; then
        skip
    fi
fi
tryload "$PERSO_BIN/autocomp_oldremote.sh" || skip
tryload "$PERSO_BIN/autocomp_remote.sh" || skip
tryload "$HOME/.local/share/bash-completion/completions/pass" || skip


# load external files
for file in 'alias' 'vars' 'funcs' 'util'; do
    if tryload "$PERSO_ENV/$file"; then
        skip
    else
        echo "$PERSO_ENV/$file not found"
    fi
done

if [ "$TERM" = 'xterm-kitty' ]; then
    alias ssh='kitty +kitten ssh'
fi

gpgconf --launch gpg-agent

eval $( opam config env )
eval $( perl \
    -I$( exercism workspace )/perl5/lib/perl5 \
    -Mlocal::lib=$( exercism workspace )/perl5 )

eval "$( starship init bash )"
export PS2='\[\033[97m\]█\[\033[0m\] '
. "$HOME/.cargo/env"

export PASSWORD_STORE_ENABLE_EXTENSIONS=true
export PASSWORD_STORE_EXTENSION_COMMANDS=crans

