#!/usr/bin/bash

# Path
PATHDIRS=(
    "$HOME/bin"
    "$HOME/.cargo/bin"
    "$HOME/.opam/default/bin"
    '/usr/local/bin'
    '/usr/bin'
    '/bin'
    '/usr/local/sbin'
    "$HOME/.local/bin"
    '/usr/bin/site_perl'
    '/usr/bin/vendor_perl'
    '/usr/bin/core_perl'
    "$HOME/.gem/ruby/2.7.0/bin"
    "$HOME/.gem/ruby/3.0.0/bin"
    "$HOME/bin/zig"
    "$HOME/.nimble/bin"
    "$HOME/.local/bin/nim/bin"
)
export PATH=$( echo "${PATHDIRS[*]}" | tr ' ' ':' )

# ctrl+o in fzf opens selected file in vim
export FZF_DEFAULT_OPTS="--bind='ctrl-o:execute(vim {})+abort'"

# edition
export EDITOR=vim
export VISUAL=vim

# GPG (signature)
export GPG_TTY="$(tty)"
export PASSWORD_STORE_ENABLE_EXTENSIONS=true

# color tweak for exa
export EXA_COLORS='*.mp3=35'

# directories in direct access
export CDPATH=".:$HOME:$HOME/School/M1/Cours:$HOME/School/M1:$HOME/.config"

# exercism cfg
export BATS_RUN_SKIPPED=true

# OCaml exception path
export OCAMLRUNPARAM=b

# Some more exhaustive environment variables
. "$PERSO_ENV/workspaces.sh"
. "$PERSO_ENV/signals.sh"
. "$PERSO_ENV/errnos/listing"

