#!/bin/bash

. "$HOME/.env/shell/keyboard"

# Beep sound removed
amixer set "Beep" 0% mute

# Dual screen management
# == Home screen ==
#xrandr --output VGA1 --right-of LVDS1 --auto
# == Aalto U. ==
#xrandr --output DP3 --auto --rotate right --left-of LVDS1
# == MPI-SWS ==
xrandr --output DP3 --auto --rotate normal --right-of LVDS1

# Font scaling
xrandr --dpi 96

# Set wallpaper
feh --bg-fill "$HOME/.config/wallpapers/deep-sea_gruv.png"

numlockx
xss-lock --transfer-sleep-lock -- betterlockscreen -l & disown

i3
