format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$cmake\
$dotnet\
$golang\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
${custom.tex}\
${custom.prolog}\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$nix_shell\
$conda\
$memory_usage\
$gcloud\
$env_var\
$crystal\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$time\
$status\
$character"""

# prompt character
[character]
success_symbol = "[█](bold green)"
error_symbol = "[█](bold red)"

# battery warning
[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[[battery.display]]
threshold = 50
style = "bold green"

# timer
[cmd_duration]
min_time = 0
show_milliseconds = true

[perl]
disabled = true

[directory]
truncation_symbol = "…/"

[status]
disabled = false
