format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$memory_usage\
$gcloud\
$env_var\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$character"""

# prompt character
[character]
success_symbol = "[█](bold green)"
error_symbol = "[█](bold red)"

# battery warning
[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[[battery.display]]
threshold = 50
style = "bold green"

# timer
[cmd_duration]
min_time = 0
show_milliseconds = true

[perl]
disabled = true

[directory]
truncation_symbol = "…/"

[status]
disabled = false

[custom.prolog]
command = "swipl --version | cut -d' ' -f3"
extensions = ["pl"]
format = "via [ v$output ](bold blue)"

[custom.tex]
command = "tex --version | head -n1 | cut -d' ' -f2"
extensions = ["tex"]
format = "via [烈](cyan)[v$output ](bold blue)"

