format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$cmake\
$dotnet\
$golang\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
${custom.tex}\
${custom.prolog}\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$nix_shell\
$conda\
$memory_usage\
$gcloud\
$env_var\
$crystal\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$time\
$status\
$character"""
