interval = 2

[theme]
theme = "semi-native"

[icons]
icons = "/home/vanille/.config/i3status-rust/icons.toml"

[[block]]
block = "toggle"
format = "$icon "
command_on = "killall -SIGUSR2 dunst; rm -f /home/nash/.config/i3status-rust/quietmode"
command_off = "killall -SIGUSR1 dunst; touch /home/nash/.config/i3status-rust/quietmode"
icon_off = "toggle_quiet_off"
icon_on = "toggle_quiet_on"
command_state = "stat /home/nash/.config/i3status-rust/quietmode 1>/dev/null 2>&1"

[[block]]
block = "sound"
format = "$icon $volume"
[[block.click]]
button = "left"
cmd = "/usr/bin/amixer -D pulse set Master 1+ toggle"
[block.theme_overrides]
idle_fg = "#665c54"

[[block]]
block = "backlight"
format = "$icon"
step_width = 5
minimum = 0
maximum = 100
cycle = [0, 50, 100, 50]
[block.theme_overrides]
idle_fg = "#665c54"

[[block]]
block = "custom"
command = "echo \"<span font='Iosevka Nerd Font 12'>󰲊</span><span font='Iosevka Nerd Font 6'> </span>\""
interval = "once"
[[block.click]]
button = "left"
cmd = "/home/nash/.env/scripts/controls/layout.sh network"
[block.theme_overrides]
idle_fg = "#689d6a"

[[block]]
block = "net"
device = "wlo1"
format = "{ssid} {signal_strength}"
missing_format = ""
[[block.click]]
button = "left"
cmd = "/home/nash/.env/scripts/controls/layout.sh network"
[block.theme_overrides]
idle_fg = "#689d6a"

[[block]]
block = "net"
device = "enp0s25"
format = "{ssid} {signal_strength}"
missing_format = ""
[[block.click]]
button = "left"
cmd = "/home/nash/.env/scripts/controls/layout.sh network"
[block.theme_overrides]
idle_fg = "#689d6a"

[[block]]
block = "cpu"
interval = 2
format = "$icon $barchart $utilization @$frequency"
[[block.click]]
button = "left"
cmd = "/home/nash/.env/scripts/controls/layout.sh procs"

[[block]]
block = "battery"
format = "$icon $percentage $time</span>"
full_format = "$icon</span>"
missing_format = "</span>"
full_threshold = 100

[[block]]
block = "memory"
format = "$icon $mem_used::$mem_total"
warning_mem = 80
critical_mem = 95
[[block.click]]
button = "left"
cmd = "/home/nash/.env/scripts/controls/layout.sh procs"

[[block]]
block = "time"
format = "$timestamp.datetime(f:'%Y-%m-%d (%a) %H:%M', l:en_US)"
[block.theme_overrides]
idle_fg = "#d3869b"
