interval = 2

[theme]
name = "semi-native"

[icons]
file = "/home/vanille/.config/i3status-rust/generated.toml"

[[block]]
block = "toggle"
text = ""
command_on = "killall -SIGUSR2 dunst; rm -f /home/vanille/.config/i3status-rust/quietmode"
command_off = "killall -SIGUSR1 dunst; touch /home/vanille/.config/i3status-rust/quietmode"
icon_off = "toggle_quiet_off"
icon_on = "toggle_quiet_on"
command_state = "stat /home/vanille/.config/i3status-rust/quietmode 1>/dev/null 2>&1"

[[block]]
block = "sound"
format = "{volume}"
on_click = "/usr/bin/amixer -D pulse set Master 1+ toggle"
[block.theme_overrides]
idle_fg = "#665c54"

[[block]]
block = "backlight"
format = ""
step_width = 5
minimum = 0
maximum = 100
cycle = [0, 50, 100, 50]
[block.theme_overrides]
idle_fg = "#665c54"

[[block]]
block = "custom"
command = "echo \"<span font='Iosevka Nerd Font 12'></span><span font='Iosevka Nerd Font 6'> </span>\""
interval = "once"
on_click = "/home/vanille/.config/scripts/network.sh"
[block.theme_overrides]
idle_fg = "#689d6a"

[[block]]
block = "net"
device = "wlo1"
format = "{ssid} {signal_strength}"
hide_missing = true
hide_inactive = true
on_click = "/home/vanille/.config/scripts/network.sh"
[block.theme_overrides]
idle_fg = "#689d6a"

[[block]]
block = "net"
device = "enp0s25"
format = "{ssid} {signal_strength}"
hide_missing = true
hide_inactive = true
on_click = "/home/vanille/.config/scripts/network.sh"
[block.theme_overrides]
idle_fg = "#689d6a"

[[block]]
block = "cpu"
interval = 2
format = "{barchart} {utilization} @ {frequency}"
on_click = "/home/vanille/.config/scripts/resources.sh"

[[block]]
block = "battery"
format = "{percentage} {time}</span>"
full_format = "</span>"
missing_format = "</span>"
full_threshold = 100

[[block]]
block = "memory"
format_mem = "{mem_used}::{mem_total}"
clickable = false
warning_mem = 80
critical_mem = 95
on_click = "/home/vanille/.config/scripts/resources.sh"

[[block]]
block = "time"
format = "%Y-%m-%d (%a) %H:%M"
[block.theme_overrides]
idle_fg = "#d3869b"
