#!/bin/bash

# Custom Rofi Script

BORDER="#b8bb26"
SEPARATOR="#FFFFFF"
FOREGROUND="#A9ABB0"
BACKGROUND="#DD000000"
BACKGROUND_ALT="#252525"
HIGHLIGHT_BACKGROUND="#98971a"
HIGHLIGHT_FOREGROUND="#FFFFFF"

BLACK="#000000"
WHITE="#ffffff"
RED="#e53935"
GREEN="#43a047"
YELLOW="#fdd835"
BLUE="#1e88e5"
MAGENTA="#00897b"
CYAN="#00acc1"
PINK="#d81b60"
PURPLE="#8e24aa"
INDIGO="#3949ab"
TEAL="#00897b"
LIME="#c0ca33"
AMBER="#ffb300"
ORANGE="#fb8c00"
BROWN="#6d4c41"
GREY="#757575"
BLUE_GREY="#546e7a"
DEEP_PURPLE="#5e35b1"
DEEP_ORANGE="#f4511e"
LIGHT_BLUE="#039be5"
LIGHT_GREEN="#7cb342"

# Launch Rofi
MENU="$(rofi -no-lazy-grab -dmenu -i -p 'Launch :' \
-hide-scrollbar true \
-bw 2 \
-lines 6 \
-line-padding 10 \
-padding 250 \
-width 60 \
-xoffset 0 -yoffset 0 \
-location 0 \
-columns 4 \
-font "Iosevka Nerd Font 12" \
-color-enabled true \
-show-icons \
-fullscreen true \
-fake-transparency \
-color-window "$BACKGROUND,$BORDER,$SEPARATOR" \
-color-normal "$BACKGROUND_ALT,$FOREGROUND,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-active "$BACKGROUND,$MAGENTA,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-urgent "$BACKGROUND,$YELLOW,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
<<< " Qutebrowser
 Firefox
 Atom
$(printf "\\u200E")ﭮ Discord
 Thunderbird
 Messenger
 GitHub
 Chromium
 Reddit
 Youtube
 Overleaf
 Gimp
 StackOverflow
 Codeforces
 Crates
 MP3 Downloader
 AUR
 Wikipedia
 Rust Playground
 Dictionary
 Mathcha
韛 DeTeXify
 Classes
 BlackBoard
 English
 MPRI
 Banque Postale
 Société Gen
龎 Manga
 Izly
 Explain Shell
 Exercism
 Godbolt
 Goubault"
)"
