#!/usr/bin/bash

# explore
alias 'ls'='exa'
alias 'll'='exa -lF -h'
alias 'la'='exa -a'
alias 'lla'='exa -la'
alias 'fda'='fd -IH'
alias 'rga'='rg -uuu'
alias 'preview'='fzf --preview "bat --color \"always\" {}"'
alias '..'='cd ..'

# updates
alias 'pacs'='sudo pacman -S'
alias 'pac++'='sudo pacman -Syu'
alias 'pac--'='sudo pacman -Rncs'
alias 'rust++'='rustup update'
alias 'git--'='git rm --cache -rf'
alias 'cleanpac'='paccache -rvk3'

# apps
alias 'btm'='btm -a'
alias 'man'='man -P "less -Q"'
alias 'ffeh'='feh -F'
alias 'less'='less -Q'

# utils
alias 'icat'='kitty +kitten icat'
alias 'xclip'="xclip -selection c"
alias 'gitnuke'='fts_gitignore_nuke'
alias 'touchall'='find . -exec touch {} +'
alias 'cx'='chmod +x'
alias 'hsync'='rsync -rhP'
alias 'hyperlinks'='/bin/ls --hyperlink=auto'
alias 'chars'='grep -o .'

# mount
alias 'mountusb'='sudo mount -o gid=users,fmask=113,dmask=002'
alias 'mountphone'='aft-mtp-mount'
alias 'ripcd'='cdda2wav -vall cddb=0 speed=4 -paranoia paraopts=proof -B -D /dev/sr0'
alias 'disk-usage'='df'

# navigation
alias 'cd_up'='cd .. && pwd && ls'
alias 'cd_prev'='cd - && pwd && ls'
export HISTIGNORE="cd_*:$HISTIGNORE"

# edition
alias 'fugitive'='vim +Gstatus +only'
