#!/usr/bin/bash

HOME="/home/vanille"

# path
export PATH="$HOME/bin:$HOME/.cargo/bin:$HOME/.opam/default/bin:usr/local/bin:/usr/bin:/bin:/usr/local/sbin:$HOME/.local/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:$HOME/.gem/ruby/2.7.0/bin"

# ctrl+o in fzf opens selected file in vim
export FZF_DEFAULT_OPTS="--bind='ctrl-o:execute(vim {})+abort'"

# edition
export EDITOR=gedit
export VISUAL=vim

# GPG (signature)
export GPG_TTY="$(tty)"

# color tweak for exa
export EXA_COLORS="*.mp3=35"

# exercism cfg
export BATS_RUN_SKIPPED=true

export WORKSPACE_0="0:<span font='InupiaqNumbers 11'></span>"
export WORKSPACE_1="1:<span font='InupiaqNumbers 11'></span>"
export WORKSPACE_2="2:<span font='InupiaqNumbers 11'></span>"
export WORKSPACE_3="3:<span font='InupiaqNumbers 11'></span>"
export WORKSPACE_4="4:<span font='InupiaqNumbers 11'></span>"
export WORKSPACE_5="5:<span font='InupiaqNumbers 11'></span>"
export WORKSPACE_6="6:<span font='InupiaqNumbers 11'></span>"
export WORKSPACE_7="7:<span font='InupiaqNumbers 11'></span>"
export WORKSPACE_8="8:<span font='InupiaqNumbers 11'></span>"
export WORKSPACE_9="9:<span font='InupiaqNumbers 11'></span>"
export WORKSPACE_X="100:×"
