" Vimrc
" Vanille (Neven Villani)

" When started as "evim", evim.vim will already have done these settings.
if v:progname =~? "evim"
  finish
endif

" Get the defaults that most users want.
source $VIMRUNTIME/defaults.vim

" plugin manager
call plug#begin()
Plug 'tpope/vim-sensible'
"Plug 'scrooloose/nerdtree'
"Plug 'mihaifm/vimpanel'
Plug 'junegunn/fzf'
Plug 'itchyny/lightline.vim'
"Plug 'terryma/vim-multiple-cursors'
Plug 'airblade/vim-gitgutter'
"Plug 'plasticboy/vim-markdown'
"Plug 'sainnhe/gruvbox-material'
Plug 'morhetz/gruvbox'
Plug 'ziglang/zig.vim'
Plug 'zah/nim.vim'
Plug 'rust-lang/rust.vim'
Plug 'whonore/Coqtail'
call plug#end()

set bg=dark
colorscheme gruvbox

let g:lightline = {
  \     'active': {
  \         'left': [['mode', 'paste' ], ['readonly', 'filename', 'modified']],
  \         'right': [['lineinfo'], ['percent'], ['fileformat', 'fileencoding']]
  \     }
  \ }

set nobackup
set noshowmode

if &t_Co > 2 || has("gui_running")
  " Switch on highlighting the last used search pattern.
  set hlsearch
endif

" Only do this part when compiled with support for autocommands.
"if has("autocmd")
"  " Put these in an autocmd group, so that we can delete them easily.
"  augroup vimrcEx
"  au!
"  " For all text files set 'textwidth' to 78 characters.
"  autocmd FileType text setlocal textwidth=78
"  augroup END
"else
  "set autoindent		" always set autoindenting on
"endif " has("autocmd")


set mouse=a

set splitbelow
set splitright

" Controls to move around splits
nnoremap <C-B> <C-W><C-J>
nnoremap <C-M> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" easy buffer closing
nnoremap <C-Q> :q<CR>
nnoremap <C-X> :x<CR>

" save
nnoremap <C-S> :w<CR>
inoremap <C-S> <ESC>:w<CR>a

" Add optional packages.
"
" The matchit plugin makes the % command work better, but it is not backwards
" compatible.
" The ! means the package won't be loaded right away but when plugins are
" loaded during initialization.
if has('syntax') && has('eval')
  packadd! matchit
endif

set belloff=all
set nofoldenable    " disable folding

" Numbering mode absolute
set number

" Indent
"   enable
set breakindent
"   wrap
set breakindentopt=shift:2,min:40,sbr
"   wrap marker
set showbreak=>>

" Move lines
"   Normal mode
nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==
"  Insert mode
inoremap <C-j> <ESC>:m .+1<CR>==gi
inoremap <C-k> <ESC>:m .-2<CR>==gi
"   Visual mode
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv"

" Completion
" normal is <C-n>
"   filepath
imap <C-f> <C-x><C-f>
"   tags
imap <C-g> <C-x><C-]>

" Exercism
command! -nargs=* ExercismSubmitRust :! exercism submit src/lib.rs

filetype indent off
set nosmartindent
set nocindent
set autoindent " repeat previous indentation
" au BufEnter *.tex :set indentkeys=
au BufEnter *.ml,*.mli :setlocal indentkeys= "0{,0},0),0],:,0#,!^F,o,O,e,0=and,0=class,0=constraint,0=done,0=else,0=end,0=exception,0=external,0=if,0=include,0=inherit,0=initializer,0=let,0=method,0=open,0=then,0=type,0=val,0=with,0;;,0>\],0\|\],0>},0\|,0},0\],0)

au BufRead,BufNewFile *.bil set filetype=bil
au BufRead,BufNewFile *.pest set filetype=pest


" Tabs
"   width
set tabstop=4
"   </> step
set shiftwidth=4
"   insert spaces
set expandtab
