#!/bin/bash

. "$HOME/.config/env/keyboard"

# Beep sound removed
amixer set "Beep" 0% mute

# Dual screen management
xrandr --output VGA1 --right-of LVDS1 --auto
# Font scaling
xrandr --dpi 96

# Set wallpaper
feh --bg-fill "$HOME/.config/wallpapers/deep-sea_gruv.png"

numlockx
xss-lock --transfer-sleep-lock -- betterlockscreen -l & disown

